version: "3.9"
services:
  app:
    build: .
    working_dir: /go/src/app
    tty: true
    volumes:
      - ../:/go/src/app
    ports:
      - 3000:3000
    environment:
      - GOARCH=amd64
      - GOOS=linux
      - HOST=0.0.0.0
      - PORT=3000
  ftp:
    image: kibatic/proftpd
    restart: unless-stopped
    environment:
      FTP_LIST: "anonymous:password"
    volumes:
      - ../ftp:/home/anonymous
