name: redoc
jobs:
  build-redoc:
    runs-on: ubuntu-latest
    name: Build Redoc document
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Redoc cli github action
        uses: seeebiii/redoc-cli-github-action@v9
        with:
          args: 'bundle swagger/serial-csv-converter.v1.yaml -o index.html'

      - name: Check build result
        run: |
          ls -al
          test -f index.html || (echo "Missing index.html from previous step." && exit 1)

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .